<a href="https://colab.research.google.com/github/devjarsaniya/Foundation-of-Machine-Learning-Numpy_Dev/blob/main/Copy_of_numpy_6_feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mat= np.array([[1,2,3],[4,5,6]])
print(mat + 10)

[[11 12 13]
 [14 15 16]]


In [ ]:
a=np.array([[1,2],[3,4]])

b=np.array([[5,6],[7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


In [ ]:
#transpose

print(a.T)

[[1 3]
 [2 4]]


In [ ]:
np.random.rand(10) #generate random number

array([0.84096631, 0.10784346, 0.02712152, 0.64754544, 0.07298381,
       0.6021181 , 0.35374299, 0.22454238, 0.93985101, 0.94245853])

In [ ]:
np.random.randint(1,100,5)#1=starting range 100=ending range 5=how many numbers to print

array([31, 17, 22, 59, 30])

In [ ]:
arr= np.arange(20)
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
#axis in numpy

arr=np.array([[10,12,14],[4,5,6]])
print(arr)

[[10 12 14]
 [ 4  5  6]]


In [ ]:
#sum
print(np.sum(arr))

51


In [ ]:
#column wise sum
print(np.sum(arr,axis=0))

[14 17 20]


In [ ]:
#row wise sum
print(np.sum(arr,axis=1))

[36 15]


In [ ]:
ar=np.array([10,-5,12,-4,-3,29])
result=np.where(ar>0,ar,0)#(condition,true,false)
print(result)


[10  0 12  0  0 29]


In [ ]:
arr=np.array([1,2,3,4,5,6])
result=np.where(arr%2!=0,-1,arr)#(condition,true,false)
print(result)

[-1  2 -1  4 -1  6]


In [ ]:
marks=np.array([10,20,32,54,76])
result=np.where(marks>35,"pass","fail")#(condition,true,false)
print(result)

['fail' 'fail' 'fail' 'pass' 'pass']


In [ ]:
data=np.array([10,20,30,40,50])

mean_value=np.mean(data)
result=np.where(data>=mean_value,-1,data)#(condition,true,false)
print(result)

[10 20 -1 -1 -1]


In [ ]:
mat=np.array([[10,60,30],[80,20,90]])

result=np.where(mat>=50,"pass","fail")#(condition,true,false)
print(result)

[['fail' 'pass' 'fail']
 ['pass' 'fail' 'pass']]


In [ ]:
import numpy as np


price=np.array([1500,3000,5000])
ds=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

#print(price.shape)
#print(price.ndim)
#print(ds.shape)
#print(ds.ndim)


In [ ]:
print(price+2)

[1502 3002 5002]


In [ ]:
result=np.dot(price,ds)
print(result)
print(np.sqrt(ds))

[40000 58500 34000 56000]
[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


In [ ]:
print(ds[1])


[5 7 4 6]


In [ ]:
print(ds[:,2])

[8 4 2]


In [ ]:
print(ds.reshape(12))

[10 15  8 12  5  7  4  6  2  3  2  4]


In [ ]:
print(ds.reshape(2,6))

[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


In [ ]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
predicted_sales=np.random.randint(0,20,size=(3,4))
print(predicted_sales)

[[15 14 11 16]
 [ 6 19  2  9]
 [ 9 15  7 13]]


In [ ]:
x=np.random.rand(5)
print(x)

[0.75420886 0.30788689 0.07953547 0.74296542 0.86295724]


In [ ]:
print(np.sum(predicted_sales))
print(np.sum(predicted_sales,axis=0))


136
[30 48 20 38]


Exercise 2
Numpy


In [ ]:
arr=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(arr)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [ ]:
print(arr.shape)
print(arr.size)
print(arr.dtype)

(5, 3)
15
int64


In [ ]:

marks_student_2 = arr[1]
print(marks_student_2)

[45 60 55]


In [ ]:

marks_subject_3 = arr[:, 2]
print(marks_subject_3)

[90 55 95 35 75]


In [ ]:

mark_student_1_subject_2 = arr[0, 1]
print(mark_student_1_subject_2)

85


In [ ]:

average_marks_per_student = np.mean(arr, axis=1)
print(average_marks_per_student)


average_marks_per_subject = np.mean(arr, axis=0)
print(average_marks_per_subject)

[84.33333333 53.33333333 91.66666667 35.         70.        ]
[61.2 69.4 70. ]


In [ ]:

updated_arr = arr + 5

print(arr)

print(updated_arr)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [ ]:

status_matrix = np.where(arr >= 50, 1, 0)

print(arr)

print(status_matrix)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [ ]:

standardized_grades_arr = np.where(arr < 40, 0, arr)

print(arr)

print(standardized_grades_arr)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


In [ ]:
grade = np.where(average_marks_per_student < 50, 0, np.where(average_marks_per_student < 70, 6, np.where(average_marks_per_student < 85 , 8, 10)))
print(grade)

[ 8  6 10  0  8]


In [ ]:
import numpy as np


electricity = np.random.randint(120, 651, size=(4, 7))
print(electricity)

[[398 601 337 410 463 489 576]
 [453 370 413 622 188 638 594]
 [239 503 166 300 322 600 389]
 [516 170 643 568 382 258 242]]


In [ ]:

print(electricity.shape)
print(electricity.ndim)
print(electricity.size)
print(electricity.dtype)

(4, 7)
2
28
int64
