<a href="https://colab.research.google.com/github/devjarsaniya/Foundation-of-Machine-Learning-Numpy_Dev/blob/main/Copy_of_numpy_6_feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
mat= np.array([[1,2,3],[4,5,6]])
print(mat + 10)

[[11 12 13]
 [14 15 16]]


In [5]:
a=np.array([[1,2],[3,4]])

b=np.array([[5,6],[7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


In [6]:
#transpose

print(a.T)

[[1 3]
 [2 4]]


In [7]:
np.random.rand(10) #generate random number

array([0.41333608, 0.70447781, 0.11417569, 0.36132954, 0.60452608,
       0.1313541 , 0.25400316, 0.85297458, 0.64190108, 0.23801802])

In [8]:
np.random.randint(1,100,5)#1=starting range 100=ending range 5=how many numbers to print

array([61, 12, 54, 89, 23])

In [9]:
arr= np.arange(20)
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [10]:
#axis in numpy

arr=np.array([[10,12,14],[4,5,6]])
print(arr)

[[10 12 14]
 [ 4  5  6]]


In [11]:
#sum
print(np.sum(arr))

51


In [12]:
#column wise sum
print(np.sum(arr,axis=0))

[14 17 20]


In [13]:
#row wise sum
print(np.sum(arr,axis=1))

[36 15]


In [14]:
ar=np.array([10,-5,12,-4,-3,29])
result=np.where(ar>0,ar,0)#(condition,true,false)
print(result)


[10  0 12  0  0 29]


In [15]:
arr=np.array([1,2,3,4,5,6])
result=np.where(arr%2!=0,-1,arr)#(condition,true,false)
print(result)

[-1  2 -1  4 -1  6]


In [16]:
marks=np.array([10,20,32,54,76])
result=np.where(marks>35,"pass","fail")#(condition,true,false)
print(result)

['fail' 'fail' 'fail' 'pass' 'pass']


In [17]:
data=np.array([10,20,30,40,50])

mean_value=np.mean(data)
result=np.where(data>=mean_value,-1,data)#(condition,true,false)
print(result)

[10 20 -1 -1 -1]


In [18]:
mat=np.array([[10,60,30],[80,20,90]])

result=np.where(mat>=50,"pass","fail")#(condition,true,false)
print(result)

[['fail' 'pass' 'fail']
 ['pass' 'fail' 'pass']]


In [19]:
import numpy as np


price=np.array([1500,3000,5000])
ds=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

#print(price.shape)
#print(price.ndim)
#print(ds.shape)
#print(ds.ndim)


In [20]:
print(price+2)

[1502 3002 5002]


In [21]:
result=np.dot(price,ds)
print(result)
print(np.sqrt(ds))

[40000 58500 34000 56000]
[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]
