<a href="https://colab.research.google.com/github/devjarsaniya/Foundation-of-Machine-Learning-Numpy_Dev/blob/main/numpy_6_feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np

In [48]:
mat= np.array([[1,2,3],[4,5,6]])
print(mat + 10)

[[11 12 13]
 [14 15 16]]


In [49]:
a=np.array([[1,2],[3,4]])

b=np.array([[5,6],[7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


In [50]:
#transpose

print(a.T)

[[1 3]
 [2 4]]


In [51]:
np.random.rand(10) #generate random number

array([0.26456263, 0.78460711, 0.56559035, 0.81688586, 0.79889636,
       0.95315916, 0.38753988, 0.60017234, 0.09189581, 0.03318593])

In [52]:
np.random.randint(1,100,5)#1=starting range 100=ending range 5=how many numbers to print

array([12, 59, 71, 73, 82])

In [53]:
arr= np.arange(20)
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [54]:
#axis in numpy

arr=np.array([[10,12,14],[4,5,6]])
print(arr)

[[10 12 14]
 [ 4  5  6]]


In [55]:
#sum
print(np.sum(arr))

51


In [56]:
#column wise sum
print(np.sum(arr,axis=0))

[14 17 20]


In [57]:
#row wise sum
print(np.sum(arr,axis=1))

[36 15]


In [58]:
ar=np.array([10,-5,12,-4,-3,29])
result=np.where(ar>0,ar,0)#(condition,true,false)
print(result)


[10  0 12  0  0 29]


In [59]:
arr=np.array([1,2,3,4,5,6])
result=np.where(arr%2!=0,-1,arr)#(condition,true,false)
print(result)

[-1  2 -1  4 -1  6]


In [60]:
marks=np.array([10,20,32,54,76])
result=np.where(marks>35,"pass","fail")#(condition,true,false)
print(result)

['fail' 'fail' 'fail' 'pass' 'pass']


In [61]:
data=np.array([10,20,30,40,50])

mean_value=np.mean(data)
result=np.where(data>=mean_value,-1,data)#(condition,true,false)
print(result)

[10 20 -1 -1 -1]


In [62]:
mat=np.array([[10,60,30],[80,20,90]])

result=np.where(mat>=50,"pass","fail")#(condition,true,false)
print(result)

[['fail' 'pass' 'fail']
 ['pass' 'fail' 'pass']]
